device:
  id: belabox-001

storage:
  path: /var/lib/belabox-metrics/metrics.db

remote:
  url: http://localhost:8080/api/metrics
  enabled: true
  upload_interval: 30s

monitoring:
  clock_skew_url: http://localhost:8428/health
  health_address: ":9100"

logging:
  level: info      # debug, info, warn, error
  format: console  # json, console

metrics:
  - name: cpu.temperature
    interval: 30s
    enabled: true

  - name: srt.packet_loss
    interval: 5s
    enabled: true

  # Bonus metrics (disabled for M1)
  - name: cpu.usage
    interval: 30s
    enabled: false

  - name: memory.available
    interval: 30s
    enabled: false
