# Development configuration
# Use this with: ./bin/tidewatch-darwin -config configs/config.dev.yaml

device:
  id: belabox-dev-001

storage:
  path: ./data/metrics/metrics.db  # Local directory for development
  wal_checkpoint_interval: 5m      # More frequent for testing
  wal_checkpoint_size_mb: 8        # Smaller threshold for testing

remote:
  url: http://localhost:8428/api/v1/import  # VictoriaMetrics import endpoint
  enabled: true
  upload_interval: 10s             # Faster uploads for testing
  batch_size: 1000                 # Smaller batches
  chunk_size: 50                   # Metrics per chunk upload
  retry:
    enabled: true
    max_attempts: 3
    initial_backoff: 1s
    max_backoff: 30s
    backoff_multiplier: 2.0
    jitter_percent: 20             # ±20% jitter

monitoring:
  clock_skew_url: http://localhost:8428/health  # Separate URL for clock skew check
  clock_skew_check_interval: 1m                  # More frequent checks
  clock_skew_warn_threshold_ms: 2000             # Warn when skew exceeds this
  health_address: ":9100"

logging:
  level: debug     # More verbose for development
  format: console  # Human-readable format

# System metrics collectors (Milestone 2)
metrics:
  - name: cpu.temperature
    interval: 10s  # Faster for testing
    enabled: true

  - name: cpu.usage
    interval: 10s
    enabled: true

  - name: memory.usage
    interval: 10s
    enabled: true

  - name: disk.io
    interval: 10s
    enabled: false  # Disabled on macOS (no /proc/diskstats)

  - name: network.traffic
    interval: 10s
    enabled: true

  - name: srt.packet_loss
    interval: 5s
    enabled: true
